name: e2e-tests

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "go.*"
      - "**/*.go"
      - ".github/workflows/*.yml"

env:
  GO_VERSION: '1.23.3'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install
        run: go install .
      - name: Run tests
        run: |
          cd tests
          ./test.sh
